export const MOCK_RECOMMENDATION = {
    nearby_restaurants: [
        {
            id: 'res_1',
            name: 'The Gilded Fork',
            image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800',
            category: 'Fine Dining',
            rating: 4.8,
            distance: '0.2 mi',
            price: '£££',
        },
        {
            id: 'res_2',
            name: 'Spice Route',
            image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=800',
            category: 'Asian Fusion',
            rating: 4.6,
            distance: '0.5 mi',
            price: '££',
        },
    ],
    nearby_hotels: [
        {
            id: 'hot_1',
            name: 'Grand Horizon Hotel',
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800',
            category: 'Luxury',
            rating: 4.9,
            distance: '0.4 mi',
            price: '££££',
        },
        {
            id: "hot_2",
            name: "The Urban Suite",
            image: "https://www.panpacific.com/content/dam/pphg-revamp/en/prsps/prc-2-0/stay/urban-suite/PRSPS_UrbanSuite_About_Room_Image.jpg",
            type: "Boutique",
            rating: 4.7,
            distance: "1.2 miles",
            price: '££££',
        },
        {
            id: "hot_3",
            name: "Azure Bay Resort",
            image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1000",
            type: "Resort",
            rating: 4.8,
            distance: "2.5 miles",
            price: '££££',
        },
    ],
    nearby_bars: [
        {
            id: 'bar_1',
            name: 'The Velvet Lounge',
            image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=800',
            category: 'Cocktail Bar',
            rating: 4.8,
            distance: '0.1 mi',
            price: '££',
        },
        {
            id: "bar_2",
            name: "Neon Nights",
            image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=1000",
            category: "Pub",
            rating: 4.5,
            distance: "0.3 miles",
            price: '££',
        },
        {
            id: "bar_3",
            name: "Craft & Cask",
            image: "https://static.where-e.com/United_Kingdom/Cask-Craft-Bar-Bottle-Shop_70a0692d6ce67d0f307c964c4c06fc84.jpg",
            category: "Brewery",
            rating: 4.6,
            distance: "0.6 miles",
            price: '££',
        },
    ]
}